### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by dimaspaf14** [janisozaur/openrct2-mingw-winnt5.1#1]
Its been 2 years since last update, idk why no more updates, any explain?

Also if you can, i want to make other open source as openloco, openttd (with jgrpp too), etc

**Comment by janisozaur** [comment]
it became too cumbersome to maintain those builds.

> i want to make other open source as openloco, openttd (with jgrpp too), etc

Feel free to use the instructions in this repo.

**Comment by dimaspaf14** [comment]
sorry for that typo, what i mean is, if you can, can you make other open source as openloco, openttd (with jgrpp too), etc to compatible with xp, because windows xp has best perfomace to my laptop

**Comment by janisozaur** [comment]
Hey, sorry, I don't think I would be making these anymore - at least not at this time. The primary reason for me to do those is work on ReactOS and not currently involved in that - and then ReactOS is getting their AppCompat layer updated, so there's even less reason. Consider upgrading your computer to Linux. If you want, you can still try building those yourself.
